# Generated by Django 6.0.7 on 2026-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("teacher", "teacher"),
                    ("student", "student"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
