# Generated by Django 6.0.7 on 2026-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                default="media/courses/default.png", upload_to="courses"
            ),
        ),
    ]
