# Generated by Django 6.0.7 on 2026-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_slug_alter_course_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(default="courses/default.png", upload_to="courses"),
        ),
    ]
