# Generated by Django 6.0.7 on 2026-08-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
