# Generated by Django 6.0.7 on 2026-08-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_alter_course_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "VIDEO"),
                            ("reading", "READING"),
                            ("pdf", "PDF"),
                        ],
                        default="pdf",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField(max_length=5000)),
                ("video_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="lesson_pdf/"),
                ),
                ("order_number", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "DRAFT"), ("published", "PUBLISHED")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["order_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "order_number"),
                        name="unique_lesson_order_per_course",
                    )
                ],
            },
        ),
    ]
