# Generated by Django 6.0.7 on 2026-09-02 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_instructor"),
        ("lesson", "0002_lesson_instructor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instructor_lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
